### ISSUE TITLE
"not a constant expression" error

### ISSUE THREAD

**Issue by kurogedelic** [aleh/a21#2]
I tried compiling but got an error.
I'm using "attiny" by David A. Mellis with ATtiny85.

	In file included from /Users/<user>/Library/Arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/avr/include/avr/io.h:99:0,
		 from /Users/<user>/Library/Arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/avr/include/avr/pgmspace.h:90,
		 from /Applications/Teensyduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28,
		 from sketch/sketch_apr02b.ino.cpp:1:
	/Users/<user>/Documents/Arduino/libraries/a21-master/a21/pins.hpp:111:45: error: 'reinterpret_cast<volatile uint8_t* {aka volatile unsigned char*}>(56)' is not a constant expression
	static constexpr volatile uint8_t *port = &PORTB;
									 ^
	/Users/<user>/Documents/Arduino/libraries/a21-master/a21/pins.hpp:113:44: error: 'reinterpret_cast<volatile uint8_t* {aka volatile unsigned char*}>(55)' is not a constant expression
	static constexpr volatile uint8_t *ddr = &DDRB;
									^
	/Users/<user>/Documents/Arduino/libraries/a21-master/a21/pins.hpp:115:43: error: 'reinterpret_cast<volatile uint8_t* {aka volatile unsigned char*}>(54)' is not a constant expression
	static constexpr volatile uint8_t *in = &PINB;

my enviroment:
Arduino IDE 1.8.13

Am I doing something wrong?

**Comment by aleh** [comment]
Thanks for reporting this!

Apparently the above happens in newer versions of Arduino IDE because of a change in GCC that does not allow constant expressions to contain pointers constructed from integers, something that port addresses are on AVR, see the discussion here, for example, https://gcc.gnu.org/bugzilla/show_bug.cgi?id=49171#c18. 

I am trying to work around this annoying rule now by using constexpr functions instead. I'll keep you posted.

**Comment by aleh** [comment]
@kurogedelic It should be working with the new version as well now, could you please try?

**Comment by kurogedelic** [comment]
@aleh Thank you.
I tried the new version. With your "NoiseChip.ino." But it can't worked. 
It shows different error messages.
The "not a constant expression" error is no longer visibled.

	Arduino：1.8.13 (Mac OS X), TD: 1.53, Board: "ATtiny25/45/85, ATtiny85, Internal 1 MHz"
	
	In file included from /Users/<user>/Documents/Arduino/libraries/a21-master/a21/pcd8544.hpp:12:0,
					 from /Users/<user>/Documents/Arduino/libraries/a21-master/a21.hpp:16,
					 from /Users/<user>/NoiseChip/NoiseChip.ino:18:
	/Users/<user>/Documents/Arduino/libraries/a21-master/a21/flashstring.hpp:11:9: error: 'fstr_t' does not name a type; did you mean 'fpos_t'?
	 typedef fstr_t *FlashStringPtr;
			 ^~~~~~
			 fpos_t
	In file included from /Users/<user>/Documents/Arduino/libraries/a21-master/a21.hpp:16:0,
					 from /Users/<user>/NoiseChip/NoiseChip.ino:18:
	/Users/<user>/Documents/Arduino/libraries/a21-master/a21/pcd8544.hpp:478:14: error: 'FlashStringPtr' has not been declared
	   void print(FlashStringPtr str) {
				  ^~~~~~~~~~~~~~
	/Users/<user>/Documents/Arduino/libraries/a21-master/a21/pcd8544.hpp:486:8: error: 'void a21::PCD8544Console<lcd, font>::print(int)' cannot be overloaded
	   void print(int n) {
			^~~~~
	/Users/<user>/Documents/Arduino/libraries/a21-master/a21/pcd8544.hpp:478:8: error: with 'void a21::PCD8544Console<lcd, font>::print(int)'
	   void print(FlashStringPtr str) {
			^~~~~
	/Users/<user>/Documents/Arduino/libraries/a21-master/a21/pcd8544.hpp:515:16: error: 'FlashStringPtr' has not been declared
	   void println(FlashStringPtr str) {
					^~~~~~~~~~~~~~
	/Users/<user>/Documents/Arduino/libraries/a21-master/a21/pcd8544.hpp:520:8: error: 'void a21::PCD8544Console<lcd, font>::println(int)' cannot be overloaded
	   void println(int n) {
			^~~~~~~
	/Users/<user>/Documents/Arduino/libraries/a21-master/a21/pcd8544.hpp:515:8: error: with 'void a21::PCD8544Console<lcd, font>::println(int)'
	   void println(FlashStringPtr str) {
			^~~~~~~
	In file included from /Users/<user>/Documents/Arduino/libraries/a21-master/a21.hpp:18:0,
					 from /Users/<user>/NoiseChip/NoiseChip.ino:18:
	/Users/<user>/Documents/Arduino/libraries/a21-master/a21/print.hpp:38:20: error: 'FlashStringPtr' has not been declared
	  static void print(FlashStringPtr str) {
						^~~~~~~~~~~~~~
	/Users/<user>/Documents/Arduino/libraries/a21-master/a21/print.hpp:46:14: error: 'static void a21::Print<T>::print(int)' cannot be overloaded
	  static void print(int n) {
				  ^~~~~
	/Users/<user>/Documents/Arduino/libraries/a21-master/a21/print.hpp:38:14: error: with 'static void a21::Print<T>::print(int)'
	  static void print(FlashStringPtr str) {
				  ^~~~~
	/Users/<user>/Documents/Arduino/libraries/a21-master/a21/print.hpp:75:22: error: 'FlashStringPtr' has not been declared
	  static void println(FlashStringPtr str) {
						  ^~~~~~~~~~~~~~
	/Users/<user>/Documents/Arduino/libraries/a21-master/a21/print.hpp:80:14: error: 'static void a21::Print<T>::println(int)' cannot be overloaded
	  static void println(int n) {
				  ^~~~~~~
	/Users/<user>/Documents/Arduino/libraries/a21-master/a21/print.hpp:75:14: error: with 'static void a21::Print<T>::println(int)'
	  static void println(FlashStringPtr str) {
				  ^~~~~~~
	exit status 1

**Comment by aleh** [comment]
@kurogedelic Hey, thanks for reporting again! 

The NoiseChip indeed fails to build for the ATtiny board definition that you are using. It turns out that Digispark (that I was targeting for ATtiny projects) has a different idea of program space string type, while yours follows the regular Arduino way. I've corrected that definition to be used only for Digispark boards, not every time an ATtiny is involved. Please pull and try building again. 

Thanks!

**Comment by aleh** [comment]
@kurogedelic Hey! Did you have a chance to test this again perhaps?

**Comment by kurogedelic** [comment]
@aleh 
I'm sorry to have you waiting.
The compilation was passed successfully.
And that works fine on my ATtiny.
Thanks for your great program.

**Comment by aleh** [comment]
Glad to hear it works! Thanks a lot!
